print("This is an example of my favorite sandwich.")
print("Make sure you have the ingredients that you need to make your favorite sandwich.")
print("Grab a plate.")
print("Put it on the counter.")
print("Walk to the fridge.")
print("Grab the package of bread.")
print("Walk back to the counter.")
print("Put the packaged bread on the counter.")
print("Open the package of bread.")
print("Take one slice of bread.")
print("Put it on the plate.")
print("Take out another slice of bread.")
print("Put the second slice of bread on the plate.")
print("Plug in the toaster.")
print("Put one slice of bread in the toaster.")
print("Put the other slice of bread in the toaster.")
print("Toast the bread.")
print("Wait.")
print("Walk to the fridge.")
print("Open the fridge.")
print("Take out the sour cream.")
print("Walk to the counter.")
print("Put the sour cream on the counter.")
print("Walk back to the fridge.")
print("Close the fridge door.")
print("Walk back to the counter.")
print("Take out one slice of toast out of the toaster.")
print("Put it on the plate.")
print("Take out the other slice of toast.")
print("Put it on the plate as well.")
print("Unplug the toaster.")
print("Walk to the sink.")
print("Grab the knife.")
print("Walk back to the counter.")
print("Grab one slice of toast.")
print("Spread the sour cream on one slice of bread.")
print("Put the knife on the plate.")
print("Fold the slice of toast with sour cream.")
print("Put the folded sandwich on the plate.")
print("Pick up the knife once again.")
print("Spread the sour cream on the other slice of toast.")
print("Put the knife on the plate.")
print("Fold the second slice toast.")
print("Put it on the plate.")
print("Pick up the knife.")
print("Walk to the sink.")
print("Put the knife in the sink.")
print("Wash your hands.")
print("Walk to the counter.")
print("Grab the sour cream.")
print("Walk to the fridge.")
print("Open the fridge.")
print("Put away the sour cream.")
print("Close the fridge.")
print("Walk to the counter.")
print("Enjoy the sandwiches!")
