print("This is an example of my favorite sandwich.")
print("Make sure you have the ingredients that you need to make your favorite sandwich.")
print("Grab a plate.")
print("Walk to the fridge.")
print("Grab the package of bread.")
print("Grab one slice of bread.")
print("Grab another slice of bread.")
print("Plug in toaster.")
print("Put one slice of bread in the toaster.")
print("Put the other slice of bread in the toaster.")
print("Toast the bread.")
print("Wait.")
print("Walk to the fridge.")
print("Take out the sour cream.")
print("Take out one slice of toast out of the toaster.")
print("Take out the other slice of toast.")
print("Turn off the toaster.")
print("Grab the knife.")
print("Spread the sour cream on one slice of bread.")
print("Fold the slice of toast with sour cream.")
print("Spread the sour cream on the other slice of bread.")
print("Fold that slice toast.")
print("Enjoy the sandwiches!")
